<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Authors>CloudShot contributors</Authors>
    <Product>CloudShot</Product>
    <Version>0.1.0-alpha.1</Version>
  </PropertyGroup>
</Project>
